services:
  - type: web
    name: qhse-safran
    runtime: docker
    region: frankfurt
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
